<a href="https://colab.research.google.com/github/Sancorti21/Reto-Pandas/blob/main/DS_C2_SC2_VICTORMANUELSANCHEZORTIZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Montado del DRIVE

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Lectura de archivo y upload de bibliotecas NumPy y PANDAS

In [ ]:
import pandas as pd
import numpy as np
pd.options.display.float_format = "{:,.0f}".format
country_vaccinations = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/0.msw7wcr3ajo0.81ve3ro2jjicountry_vaccinations.csv")
country_vaccinations

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Zimbabwe,ZWE,2022-03-25,"8,691,642","4,814,582","3,473,523","139,213","69,579",58,32,23,"4,610","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86508,Zimbabwe,ZWE,2022-03-26,"8,791,728","4,886,242","3,487,962","100,086","83,429",58,32,23,"5,528","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86509,Zimbabwe,ZWE,2022-03-27,"8,845,039","4,918,147","3,493,763","53,311","90,629",59,33,23,"6,005","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86510,Zimbabwe,ZWE,2022-03-28,"8,934,360","4,975,433","3,501,493","89,321","100,614",59,33,23,"6,667","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86511,Zimbabwe,ZWE,2022-03-29,"9,039,729","5,053,114","3,510,256","105,369","103,751",60,33,23,"6,874","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

## MOSTRAR INFORMACION RELEVANTE DEL DATA FRAME

In [ ]:
country_vaccinations.info()
country_vaccinations.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  object
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: float64(9), object(6)
memory usage: 9.9+ MB

(86512, 15)

## CONVERSION DE COLUMNA DATE (OBJECT) A DTYPE DATETIME64

In [ ]:
country_vaccinations['date'] = pd.to_datetime(country_vaccinations['date'])
country_vaccinations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  datetime64[ns]
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 9.9+ MB

## Determinar la cantidad de vacunas aplicadas de cada compañia (con base en como lo reporta cada país en la columna vaccines)

In [ ]:
vacunas_cmpy = country_vaccinations.groupby("vaccines",as_index=False
)["total_vaccinations"].sum()
vacunas_cmpy

                                             vaccines  total_vaccinations
0   Abdala, Johnson&Johnson, Oxford/AstraZeneca, P...         178,434,850
1   Abdala, Moderna, Oxford/AstraZeneca, Pfizer/Bi...      17,914,499,152
2   Abdala, Sinopharm/Beijing, Sinovac, Soberana02...         422,856,844
3                   Abdala, Soberana Plus, Soberana02       6,405,165,573
4   COVIran Barekat, Covaxin, FAKHRAVAC, Oxford/As...      10,694,796,486
..                                                ...                 ...
79                 Pfizer/BioNTech, Sinovac, Turkovac      33,923,100,933
80                         Pfizer/BioNTech, Sputnik V           3,863,380
81               QazVac, Sinopharm/Beijing, Sputnik V       3,585,428,930
82                                  Sinopharm/Beijing          30,806,707
83                       Sinopharm/Beijing, Sputnik V         645,124,308

[84 rows x 2 columns]

In [ ]:
total_acum_by_country = country_vaccinations.sort_values("date").groupby("country").last()
acum_analitico = total_acum_by_country.groupby("vaccines",as_index=False)["total_vaccinations"].sum()
acum_analitico

                                             vaccines  total_vaccinations
0   Abdala, Johnson&Johnson, Oxford/AstraZeneca, P...           9,611,936
1   Abdala, Moderna, Oxford/AstraZeneca, Pfizer/Bi...         203,144,374
2   Abdala, Sinopharm/Beijing, Sinovac, Soberana02...          37,860,994
3                   Abdala, Soberana Plus, Soberana02          35,342,367
4   COVIran Barekat, Covaxin, FAKHRAVAC, Oxford/As...         146,792,557
..                                                ...                 ...
79                 Pfizer/BioNTech, Sinovac, Turkovac         146,881,913
80                         Pfizer/BioNTech, Sputnik V              68,230
81               QazVac, Sinopharm/Beijing, Sputnik V          20,918,681
82                                  Sinopharm/Beijing             905,044
83                       Sinopharm/Beijing, Sputnik V          14,537,372

[84 rows x 2 columns]

## Obtener la cantidad de vacunas aplicadas en todo el mundo

In [ ]:
vacunas_global= total_acum_by_country["total_vaccinations"].sum()
print(f"{vacunas_global:,.0f} dosis aplicadas")

11,383,441,962 dosis aplicadas

In [ ]:
vacunas_global = acum_analitico["total_vaccinations"].sum()
print(f"{vacunas_global:,.0f} dosis aplicadas")

11,383,441,962 dosis aplicadas

## Calcular el promedio de vacunas aplicadas por país

In [ ]:
print(f"El promedio entre todos los paises {total_acum_by_country['total_vaccinations'].mean():,.2f}")
total_acum_by_country

El promedio entre todos los paises 51,046,824.94

,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
country,,,,,,,,,,,,,,
Afghanistan,AFG,2022-03-22,"5,751,015","5,082,824","4,420,127","6,868","6,319",14,13,11,159,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
Albania,ALB,2022-03-24,"2,754,244","1,278,902","1,215,199","2,541","1,821",96,45,42,634,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
Algeria,DZA,2022-03-09,"13,704,895","7,461,932","6,110,712","147,230","4,307",31,17,14,97,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",World Health Organization,https://covid19.who.int/
Andorra,AND,2022-03-13,"151,997","57,817","53,367","1,973",34,196,75,69,440,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",World Health Organization,https://covid19.who.int/
Angola,AGO,2022-03-25,"17,535,411","11,235,059","5,993,792",NaN,"34,171",52,33,18,"1,007",Oxford/AstraZeneca,World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wales,OWID_WLS,2022-03-28,"6,927,437","2,528,664","2,399,341","2,254","1,609",219,80,76,508,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
Wallis and Futuna,WLF,2022-03-28,"13,073","6,483","6,457",NaN,19,118,58,58,"1,713",Moderna,SPC Public Health Division,https://stats.pacificdata.org/vis?tm=covid&pg=...
Yemen,YEM,2022-03-16,"807,502","643,501","404,781",NaN,"2,271",3,2,1,74,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac",World Health Organization,https://covid19.who.int/
Zambia,ZMB,2022-03-29,"3,402,612","2,829,929","2,182,849","12,073","13,650",18,15,12,721,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm...",Government of Zambia,https://rtc-planning.maps.arcgis.com/apps/dash...
Zimbabwe,ZWE,2022-03-29,"9,039,729","5,053,114","3,510,256","105,369","103,751",60,33,23,"6,874","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

## El promedio por pais de acuerdo a la aplicacion de vacunas diarias

In [ ]:
prom_pais = (country_vaccinations.groupby("country")["daily_vaccinations"].mean().round(2))
prom_pais

country
Afghanistan         14,611
Albania              6,276
Algeria             33,904
Andorra                368
Angola              44,821
                     ...
Wales               15,518
Wallis and Futuna       34
Yemen                2,556
Zambia               9,650
Zimbabwe            21,669
Name: daily_vaccinations, Length: 223, dtype: float64

## Determinar la cantidad de vacunas aplicadas el dia 29/01/21 en todo el mundo

In [ ]:
total_vacunas = country_vaccinations.loc[
    country_vaccinations["date"] == "2021-01-29",
    "daily_vaccinations"].sum()

print(f"Total de vacunas aplicadas en el mundo el día 29/01/2021: {total_vacunas:,.0f}")

Total de vacunas aplicadas en el mundo el día 29/01/2021: 4,884,052

## Crear un dataframe nuevo denominado conDiferencias que contenga los datos originales y una columna derivada (diferencias) con las diferencias de aplicación entre las columnas daily_vaccinations y daily_vaccinations_raw.

In [ ]:
conDiferencias = country_vaccinations.copy()
conDiferencias["diferencias"] = conDiferencias["daily_vaccinations"] - conDiferencias["daily_vaccinations_raw"]
conDiferencias

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,diferencias
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Zimbabwe,ZWE,2022-03-25,"8,691,642","4,814,582","3,473,523","139,213","69,579",58,32,23,"4,610","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,"-69,634"
86508,Zimbabwe,ZWE,2022-03-26,"8,791,728","4,886,242","3,487,962","100,086","83,429",58,32,23,"5,528","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,"-16,657"
86509,Zimbabwe,ZWE,2022-03-27,"8,845,039","4,918,147","3,493,763","53,311","90,629",59,33,23,"6,005","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,"37,318"
86510,Zimbabwe,ZWE,2022-03-28,"8,934,360","4,975,433","3,501,493","89,321","100,614",59,33,23,"6,667","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,"11,293"
86511,Zimbabwe,ZWE,2022-03-29,"9,039,729","5,053,114","3,510,256","105,369","103,751",60,33,23,"6,874","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,"-1,618"

## Obtener el periodo de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua.

In [ ]:
periodo = (country_vaccinations["date"].max() - country_vaccinations["date"].min()).days
print(f"Periodo entre el registro más antiguo y el más reciente: {periodo} días")

Periodo entre el registro más antiguo y el más reciente: 482 días

## Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac) con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter , ).

In [ ]:
conCantidad = country_vaccinations.copy()
conCantidad["canVac"] = conCantidad["vaccines"].str.split(", ").str.len()
conCantidad

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,canVac
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Zimbabwe,ZWE,2022-03-25,"8,691,642","4,814,582","3,473,523","139,213","69,579",58,32,23,"4,610","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,4
86508,Zimbabwe,ZWE,2022-03-26,"8,791,728","4,886,242","3,487,962","100,086","83,429",58,32,23,"5,528","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,4
86509,Zimbabwe,ZWE,2022-03-27,"8,845,039","4,918,147","3,493,763","53,311","90,629",59,33,23,"6,005","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,4
86510,Zimbabwe,ZWE,2022-03-28,"8,934,360","4,975,433","3,501,493","89,321","100,614",59,33,23,"6,667","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,4
86511,Zimbabwe,ZWE,2022-03-29,"9,039,729","5,053,114","3,510,256","105,369","103,751",60,33,23,"6,874","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,4

## Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020.

In [ ]:
antes20 = country_vaccinations.query('date < "2020-12-20"')
antes20

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
13403,Canada,CAN,2020-12-14,5,5,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13404,Canada,CAN,2020-12-15,727,727,NaN,722,722,0,0,NaN,19,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13405,Canada,CAN,2020-12-16,"3,025","3,025",NaN,"2,298","1,510",0,0,NaN,40,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13406,Canada,CAN,2020-12-17,"7,279","7,279",NaN,"4,254","2,425",0,0,NaN,64,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
13407,Canada,CAN,2020-12-18,"11,296","11,296",NaN,"4,017","2,823",0,0,NaN,74,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Official data from provinces via covid19tracke...,https://covid19tracker.ca/vaccinationtracker.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82362,United States,USA,2020-12-15,"84,638","76,984","6,281","49,771","27,175",0,0,0,82,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://data.cdc.gov/Vaccinations/COVID-19-Vac...
82363,United States,USA,2020-12-16,"244,549","231,496","6,757","159,911","71,420",0,0,0,215,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://data.cdc.gov/Vaccinations/COVID-19-Vac...
82364,United States,USA,2020-12-17,"517,161","496,980","7,507","272,612","121,718",0,0,0,367,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://data.cdc.gov/Vaccinations/COVID-19-Vac...
82365,United States,USA,2020-12-18,"933,551","904,656","8,718","416,390","180,653",0,0,0,544,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://data.cdc.gov/Vaccinations/COVID-19-Vac...
82366,United States,USA,2020-12-19,"1,115,437","1,082,608","9,778","181,886","180,858",0,0,0,545,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://data.cdc.gov/Vaccinations/COVID-19-Vac...

## Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer.

In [ ]:
pfizer = country_vaccinations[country_vaccinations["vaccines"].str.contains("Pfizer")]
pfizer

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0,0,NaN,NaN,NaN,0,0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,"1,367",NaN,NaN,NaN,34,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85069,Wales,OWID_WLS,2022-03-24,"6,921,195","2,526,832","2,397,677","1,756","1,705",218,80,76,538,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
85070,Wales,OWID_WLS,2022-03-25,"6,923,298","2,527,100","2,398,097","2,103","1,667",218,80,76,526,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
85071,Wales,OWID_WLS,2022-03-26,"6,923,706","2,527,184","2,398,322",408,"1,519",218,80,76,479,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
85072,Wales,OWID_WLS,2022-03-27,"6,925,183","2,528,051","2,398,676","1,477","1,505",218,80,76,475,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...
85073,Wales,OWID_WLS,2022-03-28,"6,927,437","2,528,664","2,399,341","2,254","1,609",219,80,76,508,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/vaccin...

## Almacenar los dataframes generados (conDiferencias, conCantidad, antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx, donde cada dataframe ocupe una hoja diferente.

In [ ]:
with pd.ExcelWriter("resultadosReto.xlsx") as excel:
    conDiferencias.to_excel(excel, sheet_name="conDiferencias", index=False)
    conCantidad.to_excel(excel, sheet_name="conCantidad", index=False)
    antes20.to_excel(excel, sheet_name="antes20", index=False)
    pfizer.to_excel(excel, sheet_name="pfizer", index=False)

In [ ]:
!ls

drive  resultadosReto.xlsx  sample_data

In [ ]:
from google.colab import files
files.download("resultadosReto.xlsx")

##